Fix/camera example
openkraken/plugins pull request #6
Opened 2021-04-19 09:03 UTC by ReverseScale

The packages/kraken_camera Plugin is modified as follows:
1. Modify the registration tag type
2. Add swift bridge file
3. Supplement example bundle.js

2021-04-19 09:07 UTC, andycall requested changes

2021-04-19 09:07 UTC, andycall commented on packages/kraken_camera/lib/camera.dart
> +      print("保存成功, 路径为 $path");
日志输出需要删掉

2021-04-19 09:10 UTC, wssgcg1213 requested changes
还有一些代码风格的提交, 建议遵循原状

2021-04-19 09:10 UTC, wssgcg1213 commented on packages/kraken_camera/lib/camera.dart
> +      print("保存成功, 路径为 $path");
去掉 print

2021-04-19 09:10 UTC, wssgcg1213 commented on packages/kraken_camera/lib/camera_element.dart
> +  bool isFallback = true;
这个属性貌似没有使用?

2021-04-19 09:10 UTC, wssgcg1213 commented on packages/kraken_camera/lib/camera_element.dart
> +  bool isFallback = true;
可以删除这个

2021-04-19 09:10 UTC, wssgcg1213 commented on packages/kraken_camera/lib/camera_element.dart
> +  Future<void> _setProperty(String key, dynamic value) {
这里不需要使用 Future

2021-04-19 11:07 UTC, ReverseScale commented
好滴，已经调整一波了

2021-04-20 03:47 UTC, wssgcg1213 approved these changes

2021-04-20 03:48 UTC, andycall approved these changes

2021-04-20 03:48 UTC, merged

2021-04-20 05:41 UTC, andycall commented
已发布到 pub.dev 

https://pub.dev/packages/kraken_camera